// <auto-generated />
using System;
using FitnessTreker_v1._0._2_OLYU.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTreker_v1._0._2_OLYU.Migrations.GymMigrations
{
    [DbContext(typeof(Gym))]
    [Migration("20240305175004_Gym_1")]
    partial class Gym_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartEndWH")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkoutScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelegramId")
                        .HasColumnType("int");

                    b.Property<int>("VisitingsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitingsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.Visiting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsVisited")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Visitings");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutScheduleId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.WorkoutSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("VisitingId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitingId");

                    b.ToTable("WorkoutSchedules");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.Schedule", b =>
                {
                    b.HasOne("FitnessTreker_v1._0._2_OLYU.Models.WorkoutSchedule", null)
                        .WithMany("Schedules")
                        .HasForeignKey("WorkoutScheduleId");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.User", b =>
                {
                    b.HasOne("FitnessTreker_v1._0._2_OLYU.Models.Visiting", "Visitings")
                        .WithMany("Users")
                        .HasForeignKey("VisitingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitings");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.Workout", b =>
                {
                    b.HasOne("FitnessTreker_v1._0._2_OLYU.Models.WorkoutSchedule", "WorkoutSchedules")
                        .WithMany("Workouts")
                        .HasForeignKey("WorkoutScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSchedules");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.WorkoutSchedule", b =>
                {
                    b.HasOne("FitnessTreker_v1._0._2_OLYU.Models.Visiting", null)
                        .WithMany("WorkoutSchedules")
                        .HasForeignKey("VisitingId");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.Visiting", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("WorkoutSchedules");
                });

            modelBuilder.Entity("FitnessTreker_v1._0._2_OLYU.Models.WorkoutSchedule", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Workouts");
                });
#pragma warning restore 612, 618
        }
    }
}
